
const IP_TERMS: readonly string[] = [
  'mario', 'luigi', 'princess peach', 'bowser', 'yoshi', 'wario', 'waluigi', 'rosalina',
  'donkey kong', 'diddy kong',
  'zelda', 'ganondorf', 'sheik', 'hyrule',
  'kirby', 'samus', 'metroid', 'pikmin',
  'pokemon', 'pokémon', 'pikachu', 'charizard', 'eevee', 'mewtwo',
  'bulbasaur', 'squirtle', 'charmander', 'jigglypuff', 'snorlax', 'gengar',
  'splatoon', 'inkling',
  'animal crossing', 'isabelle animal',
  'super smash',
  'sonic', 'sonic the hedgehog', 'sonic hedgehog',
  'tails sonic', 'knuckles sonic', 'shadow the hedgehog',
  'amy rose', 'doctor eggman', 'robotnik',
  'mickey mouse', 'minnie mouse', 'donald duck', 'goofy disney', 'disney pluto',
  'frozen elsa', 'frozen anna', 'olaf disney',
  'lion king', 'simba',
  'aladdin disney', 'jasmine disney',
  'little mermaid', 'ariel disney',
  'beauty and the beast', 'belle disney',
  'cinderella disney', 'snow white disney',
  'pocahontas disney', 'mulan disney', 'moana disney', 'tarzan disney',
  'toy story', 'buzz lightyear', 'woody toy',
  'lightning mcqueen',
  'finding nemo', 'finding dory',
  'wall-e', 'wall e',
  'monsters inc', 'sully monsters',
  'inside out',
  'ratatouille', 'remy ratatouille',
  'pixar coco',
  'incredibles',
  'spider-man', 'spider man', 'spiderman',
  'iron man', 'ironman',
  'captain america', 'cap america',
  'thor marvel', 'hulk marvel', 'avengers',
  'black widow', 'hawkeye',
  'deadpool', 'wolverine',
  'x-men', 'magneto', 'professor x',
  'venom marvel', 'thanos',
  'doctor strange', 'ant-man',
  'guardians of the galaxy',
  'black panther',
  'batman', 'bruce wayne',
  'superman', 'clark kent', 'lex luthor',
  'wonder woman',
  'the flash', 'aquaman',
  'green lantern', 'harley quinn',
  'joker dc',
  'naruto', 'sasuke', 'kakashi',
  'goku', 'vegeta', 'dragon ball', 'dbz',
  'one piece', 'luffy', 'zoro',
  'doraemon',
  'sailor moon',
  'totoro', 'ghibli', 'spirited away', 'no face ghibli',
  'attack on titan', 'eren yeager',
  'demon slayer', 'tanjiro', 'nezuko',
  'jujutsu kaisen', 'gojo',
  'my hero academia', 'deku',
  'death note',
  'hello kitty', 'sanrio', 'kuromi', 'cinnamoroll', 'my melody', 'pompompurin',
  'hatsune miku', 'miku', 'mikuu', 'vocaloid',
  'kagamine rin', 'kagamine len', 'megurine luka',
  'kasane teto',
  'star wars', 'darth vader', 'yoda', 'baby yoda', 'grogu', 'mandalorian',
  'luke skywalker', 'leia', 'princess leia', 'han solo',
  'stormtrooper', 'kylo ren', 'r2-d2', 'bb-8',
  'harry potter', 'hogwarts', 'dumbledore', 'voldemort', 'hermione',
  'minecraft', 'creeper minecraft',
  'pac-man', 'pacman', 'pac man',
  'tetris',
  'fortnite',
  'among us', 'amongus',
  'roblox',
  'angry birds',
  'fall guys',
  'overwatch tracer', 'overwatch genji', 'overwatch d.va',
  'undertale sans', 'undertale frisk',
  'fnaf', 'five nights at freddy',
  'cuphead',
  'celeste game',
  'shrek',
  'spongebob', 'patrick star spongebob', 'squidward',
  'simpsons', 'homer simpson', 'bart simpson',
  'south park',
  'family guy',
  'rick and morty',
  'bluey',
  'paw patrol',
  'peppa pig',
  'adventure time', 'finn the human', 'jake the dog',
  'powerpuff girls',
  'minions',
  'transformers', 'optimus prime',
  'teenage mutant ninja turtles', 'tmnt',
  'my little pony',
  'looney tunes', 'bugs bunny', 'daffy duck',
] as const

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

const IP_REGEX = (() => {
  const escaped = IP_TERMS.map(t => escapeRegex(t.toLowerCase()))
  return new RegExp(`\\b(?:${escaped.join('|')})\\b`, 'i')
})()

export function looksLikeProtectedIP(...parts: Array<string | null | undefined>): boolean {
  const joined = parts.filter(Boolean).join(' ').trim()
  if (!joined) return false
  return IP_REGEX.test(joined)
}
